site_name: AutoMIL
site_author: Jonas Waibel
site_description: A framework for training and evaluating Multiple Instance Learning (MIL) models on Whole Slide Images (WSIs).

repo_url: https://github.com/WaibelJonas/AutoMIL/
copyright: Copyright &copy; 2025 - 2026 Jonas Waibel

theme:
  name: material
  palette:
    scheme: automil
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - content.code.copy


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_signature_annotations: true
            show_root_heading: true
            show_object_full_path: false
            filters:
              - "!^_"

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getstarted/installation.md
    - Quick Start: getstarted/quickstart.md
    - Requirements: getstarted/requirements.md
  - API:
    - CLI: api/cli.md
    - Project: api/project.md
    - Dataset: api/dataset.md
    - ModelManager: api/model.md
    - Trainer: api/trainer.md
    - Evaluator: api/evaluation.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WaibelJonas

extra_css:
  - stylesheets/extra.css